contact/urls.py
from django.urls import path
from contact.views import ContactListView, ContactDetailView

app_name = 'contact'

urlpatterns = [
    path('', ContactListView.as_view(), name='index'),
    path('contact/<int:pk>/', ContactDetailView.as_view(), name='contact_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name

class Contact(models.Model):
    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'
    

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404
from contact.models import Contact
from django.views.generic import ListView, DetailView

class ContactListView(ListView):
    model = Contact
    template_name = 'contact/index.html'
    context_object_name = 'contacts'
    paginate_by = 10

    def get_queryset(self):
        return Contact.objects.filter(show=True).order_by('-id')


class ContactDetailView(DetailView):
    model = Contact
    template_name = 'contact/contact.html'
    context_object_name = 'contact'

    def get_object(self):
        contact_id = self.kwargs.get('pk')
        single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
        self.site_title = f'{single_contact.first_name} {single_contact.last_name} - '
        return single_contact

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>E-mail:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name }}</p>
  </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
    
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts   
            </caption>

            <thead>
                <tr>
                    <th>ID</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Phone</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in contacts %}
                    <tr class="table-row">
                        <td class="table-cel">
                            <a class="table-link" href="{% url 'contact:contact_detail' pk=contact.pk %}">
                                {{contact.id}}
                            </a>
                        </td>
                        <td class="table-cel">
                            {{contact.first_name}}
                        </td>
                        <td class="table-cel">
                            {{contact.last_name}}
                        </td>
                        <td class="table-cel">
                            {{contact.phone}}
                        </td>
                        <td class="table-cel">
                            {{contact.email}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}